### ISSUE TITLE
Switch to official jasmine-core as oppose to jasmine-node

### ISSUE THREAD

**Issue by paazmaya** [jribble/grunt-jasmine-node-coverage#35]
https://www.npmjs.com/package/jasmine-core
https://github.com/jasmine/jasmine/blob/master/release_notes/20.md#better-nodejs-support

**Comment by lebolo** [comment]
:+1:

**Comment by noahsw** [comment]
+1. My tests pass using https://github.com/onury/grunt-jasmine-nodejs but not with this task.

**Comment by coryellenberger** [comment]
I've been looking for a task that can run my NodeJS jasmine specs with istanbul coverage. Unfortunately this one requires an older version of jasmine than what I am using. Have you seen any forks with jasmine 2 or higher?

**Comment by paazmaya** [comment]
Done, going to be in `v1.0.0` release
