### ISSUE TITLE
Coverage check is not executed if the task is not exiting process

### ISSUE THREAD

**Issue by Andre-Gl** [jribble/grunt-jasmine-node-coverage#40]
Coverage check is not executed if the task is not exiting process like in case of failed tests.
So if tests are successful coverage check is not executed.
Probably this happens because it is executed in exit handler:
`process.once('exit', exitHandler);`

**Comment by paazmaya** [comment]
Good point. PR?

**Comment by paazmaya** [comment]
Fix provided in #41 merged via cc8f9b4e78e275f22e4e6ab5502704132d19cfd6

**Comment by Andre-Gl** [comment]
Could you publish it please?

**Comment by paazmaya** [comment]
Sure!

**Comment by Andre-Gl** [comment]
Thanks!
