### ISSUE TITLE
No coverage when using coverage.reportDir option

### ISSUE THREAD

**Issue by dhaub** [jribble/grunt-jasmine-node-coverage#42]
A simple way to test this is to add: reportDir: "build/" to the coverage options on this project.  The directory will be created and populated with files but with no coverage information in them.  The output to the console also has no coverage data.

Make sure the "coverage" directory is deleted before running, as the console output tends to read data from that directory.

**Comment by paazmaya** [comment]
Did removing the directory solve the issue?

**Comment by dhaub** [comment]
Here are different testing conditions:
1. No reportDir in Gruntfile.js =>  "coverage" directory is created and
populated correctly.
2. ReportDir="build" in Gruntfile.js, no "coverage" directory on filesystem
=> "build" dir has index.html but no actual coverage data, no data output
to console.  This is wrong.
3. ReportDir="build" in Gruntfile.js, "coverage" directory exists on
filesystem and is populated => "build" dir has index.html with correct
coverage data.  This result is right but for the wrong reason.

Hope this helps.

**Comment by paazmaya** [comment]
Please try release `v0.4.1` and let me know if it got fixed

**Comment by dhaub** [comment]
That fixed it.  Thanks!
