### ISSUE TITLE
shows coverage of my test not my source?

### ISSUE THREAD

**Issue by joseph-jja** [jribble/grunt-jasmine-node-coverage#43]
You can see the coverage here

https://github.com/joseph-jja/grunt-minify-each/tree/master/coverage

Gruntfile here https://github.com/joseph-jja/grunt-minify-each/blob/master/Gruntfile.js

did I do something wrong?

**Comment by paazmaya** [comment]
Have a go with `v1.0.0` and see if that solves this issue.

**Comment by paazmaya** [comment]
Closing as old and possibly unrelated anymore.
Feel free to re-open if valid.
