### ISSUE TITLE
What about EcmaScript Harmony ?

### ISSUE THREAD

**Issue by MathRobin** [jribble/grunt-jasmine-node-coverage#44]
When using generators in tested modules, I got :

[SyntaxError: myFile.js:18
function *theFunction() {
              ^
Unexpected token *]

**Comment by noahsw** [comment]
I transpile with Babel first and then run my tests on the ES5 files. Not ideal but it works.

**Comment by MathRobin** [comment]
Yes but definitely not really a "great" solution...

**Comment by paazmaya** [comment]
Outside the scope of this tool, currently needs Babel or some other tool in between, as long as Node.js does not support it natively.
