### ISSUE TITLE
Support for the Istanbul include-all-sources option

### ISSUE THREAD

**Issue by JonUK** [jribble/grunt-jasmine-node-coverage#45]
Hi,

Can you please add support for the --include-all-sources Istanbul flag so that the coverage report covers all code files regardless of whether they are covered by a test or not.

Thanks

Jon

**Comment by paazmaya** [comment]
Which version introduces this?
Would you like to create a PR with that feature?

**Comment by dosht** [comment]
+1
I found that If I wrote only one test for only one module, it will report coverage of 100%.
I had to require all modules I want to cover in one of the test files otherwise.

**Comment by pdapel** [comment]
+1, just bumped into this myself

**Comment by paazmaya** [comment]
PR is more than welcome

**Comment by paazmaya** [comment]
> Which version introduces this?

**Comment by paazmaya** [comment]
https://github.com/jribble/grunt-jasmine-node-coverage/blob/master/README.md#optionscoverage available via `v1.0.0`
