### ISSUE TITLE
Jasmine-node 2.x support?

### ISSUE THREAD

**Issue by dmamaril** [jribble/grunt-jasmine-node-coverage#48]
Curious as to how to get this to work / configure properly to work with Jasmine 2.x

**Comment by paazmaya** [comment]
PR more than welcome, since unfortunately haven't had the time to look at it...

**Comment by mbielski** [comment]
Looks like it should be as simple as changing your references from `jasmine-node` to `grunt-jasmine-nodejs`. Of course, it's probably not that simple.

**Comment by paazmaya** [comment]
Could this be demoed via PR?

**Comment by mbielski** [comment]
I'll see if I can find the time. No promises.

**Comment by paazmaya** [comment]
Jasmine core going to be in `v1.0.0` release
