### ISSUE TITLE
Support for the Istanbul --preserve-comments option

### ISSUE THREAD

**Issue by Gravey92** [jribble/grunt-jasmine-node-coverage#51]
At present, this package does not play nicely with the multiline node package for creating multi-line strings. By default, istanbul strips out comments (which multiline relies on), causing coverage to break when mutli-line strings are encountered.

It would be nice to have this option exposed as opposed to refactoring my source code to not use multiline.

Thanks,
David

**Comment by paazmaya** [comment]
Pull Request more than welcome to add this functionality

**Comment by paazmaya** [comment]
Check the functionalities of `v1.0.0` and see if this can now be done easier

**Comment by paazmaya** [comment]
Closing as inactive
