### ISSUE TITLE
Module load hook problems when using other tasks

### ISSUE THREAD

**Issue by zoltan-mihalyi** [jribble/grunt-jasmine-node-coverage#52]
When I run the coverage task with other tasks, and a previous task required a module, the module load hook does not run for the module and doesn't instrument it.

After the end of the coverage task, the module load hook is still active, therefore required modules in further tasks are instrumented.

**Comment by paazmaya** [comment]
Working example configuration, which could be added to the test cases?

**Comment by zoltan-mihalyi** [comment]
Here is the configuration:
https://gist.github.com/zoltan-mihalyi/a0709f2ec78fb8ae0def7271074c7d0e

As you can see in the log when runnig grunt:
- before.js is not instrumented, because it is loaded in a previous step. We should see it is unloaded and loaded again instrumented. (And if the task "before" is running again, the should see it is loaded again not instrumented)
- after.js is instrumented, however it is loaded after the task is finished. We should see it is not instrumented.

**Comment by paazmaya** [comment]
Have a go with `v1.0.0` and see what changed, if any

**Comment by zoltan-mihalyi** [comment]
It solves the problam, thanks!

**Comment by paazmaya** [comment]
Thank you for coming back with the information
