### ISSUE TITLE
Publish new version to npm repository

### ISSUE THREAD

**Issue by nirnatan** [jribble/grunt-jasmine-node-coverage#61]
Hey Jarrod,
Can you please update npmjs repository with the new version that supports grunt 0.4.5?

**Comment by jmpresso** [comment]
Seconded- would love to use, but we have too many grunt dependencies that depend on 0.4.5

**Comment by paazmaya** [comment]
https://www.npmjs.com/package/grunt-jasmine-node-coverage

```
published 14 minutes ago
1.2.0 is the latest of 23 releases 
```
