### ISSUE TITLE
Support for JUnitXmlReporter

### ISSUE THREAD

**Issue by elliotrodriguez** [jribble/grunt-jasmine-node-coverage#63]
I would like to add support for JUnitXmlReporter using the jasmine-reporters module.

**Comment by jmpresso** [comment]
Pull request 62 is now submitted for this
https://github.com/jribble/grunt-jasmine-node-coverage/pull/64

**Comment by jmpresso** [comment]
Opened a pull request for this- https://github.com/jribble/grunt-jasmine-node-coverage/pull/65

**Comment by paazmaya** [comment]
#65 has been merged

**Comment by haoruiqian** [comment]
When will you push this feature to npm repository?

**Comment by jmpresso** [comment]
@paazmaya - Still could use a release here, when you get a chance

**Comment by paazmaya** [comment]
Hi, sorry for the delay. Will happen now.

**Comment by paazmaya** [comment]
https://www.npmjs.com/package/grunt-jasmine-node-coverage
`v2.0.0` is out there, but the dependency of `jasmine` version `2.5.3` was no good, it needs to be `2.5.2` which will be in `v2.0.1` going out in a minute.
