### ISSUE TITLE
Getting issue while installing NPM Please help

### ISSUE THREAD

**Issue by dinarrao** [jribble/grunt-jasmine-node-coverage#67]
D:\abc\angular\my-app>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! path D:\abc\angular\my-app\node_modules\protractor\node_modules\jasmine\bin\jasmine.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\abc\angular\my-app\node_modules\protractor\node_modules\jasmine\bin\jasmine.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abc\AppData\Roaming\npm-cache\_logs\2018-03-19T19_08_19_341Z-debug.log

**Comment by paazmaya** [comment]
Sorry, but according to what is shown there, it is not related to the functionality of this project.
Hope you have googled the error code...
