### ISSUE TITLE
i am getting following error when run 'npm test'

### ISSUE THREAD

**Issue by Sushmaemmadi** [jribble/grunt-jasmine-node-coverage#68]
npm ERR! path /Users/xxxx/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/xxxx/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

Please help me out from this

**Comment by paazmaya** [comment]
Looks like you are in wrong directory when it comes to using any npm project. Change the current directory to wherever you have the project cloned.
