### ISSUE TITLE
Issue related to async-await

### ISSUE THREAD

**Issue by elpibeperez** [jribble/grunt-jasmine-node-coverage#70]
When I code using async await, Istambul breaks because it is using an old version of esprima. If esprima is updated in istanbul to version 4.0.x, the issues disapear. If istanbul is updated to 1.0, 
I opened an issue to the istanbul people, but they don't seem to be doing any changes to 0.4.x.

**Comment by paazmaya** [comment]
Where is `4.0.x` available, https://github.com/gotwarlost/istanbul/releases?
